### ISSUE TITLE
upon start there is an error and crash

### ISSUE THREAD

**Issue by DanHolli** [ogra1/hdmi-usb-dongle#2]
running in Gnome under Wayland

```
No matching audio device found, moving on without sound !!
Traceback (most recent call last):
  File "/snap/hdmi-usb-dongle/33/usr/bin/trayicon", line 4, in <module>
    import pystray
  File "/snap/hdmi-usb-dongle/33/lib/python3.8/site-packages/pystray/__init__.py", line 48, in <module>
    Icon = backend().Icon
  File "/snap/hdmi-usb-dongle/33/lib/python3.8/site-packages/pystray/__init__.py", line 40, in backend
    return importlib.import_module(__package__ + '._' + module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/snap/hdmi-usb-dongle/33/lib/python3.8/site-packages/pystray/_xorg.py", line 36, in <module>
    display = Xlib.display.Display()
  File "/snap/hdmi-usb-dongle/33/lib/python3.8/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/snap/hdmi-usb-dongle/33/lib/python3.8/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/snap/hdmi-usb-dongle/33/lib/python3.8/site-packages/Xlib/protocol/display.py", line 166, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0": b'Authorization required, but no authorization protocol specified\n'
```

**Comment by DanHolli** [comment]
i missed the mention of the config location .after setting it up with just the device it worked
